[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

.config.toml for Terrain Recognition:

[theme]
base="dark"
primaryColor="#FFAA00"
backgroundColor="#0F2027"
secondaryBackgroundColor="#203A43"
textColor="#FFFFFF"
font="sans serif"
